name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push the Docker image to ACR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./TP3/Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20230996:${{ github.sha }}

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
        --resource-group ${{ secrets.RESOURCE_GROUP }} \
        --name 20230996 \
        --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/20230996:${{ github.sha }} \
        --dns-name-label devops-${{ ID_EFREI}} \
        --location germanywestcentral \
        --registry-username ${{ secrets.REGISTRY_USERNAME }} \
        --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
        --environment-variables API_KEY=${{ secrets.API_KEY }}

